package taniaGama.com.br.enums;

public enum DoceCategoria {
	
	DOCINHOBOLINHASIMPLES, DOCINHOBOLINHALUXO, DOCINHOBOLINHAGOURMET, DOCINHOCOPINHO, BRIGADEIROCOLHER, CUPCAKES, DOCEDIVERSOS, TORTAS, BEIJINHOUVA

}
